name: 'Maven dependency cleaner'
description: 'Cleans unused maven dependencies'
inputs:
  m2-path:
    description: "M2 Path"
    required: false
    default: "~/.m2/repository"

runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
  post-if: "success()"
